const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const port = process.env.PORT || 8081;
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static(`${__dirname}/public`));
require('./app/routes')(app);
app.listen(port);
console.log(`Magic happens on port ${port}`);
exports = module.exports = app;
